/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;

import Conexao.Conexao;
import Model.Agencia;
import Model.Banco;
import Model.Conta;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class GerenciaBanco extends javax.swing.JFrame {

    private static Banco banco;
    private static String nomeBanco;
    
    
    DefaultListModel conList = null;
    DefaultListModel  agList = null; 
    
     
    public GerenciaBanco(String nomeBanco) {
        initComponents();
        this.nomeBanco = nomeBanco;
        textNome.setText(nomeBanco);
        receberAgencias();
       
    }
    
    public void receberAgencias(){
        
        Conexao conexao = new Conexao(2525);
        try{
            
            conexao.conectaServidor();
            
            conexao.enviaString("dadosAgencia");
            conexao.enviaString(nomeBanco);
             
            String result = "";
            result = conexao.recebeString();
            
            agList = new DefaultListModel();
           
            if(result!=null){
                String[] quebra = result.split("&&");
               
                for(int i=0; i<quebra.length; i++){
                    
                    agList.add(i, quebra[i]);
                }
                 
            }
            jListAgencias.setModel(agList);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro na busca de agencias");
        }finally{
            if(conexao.isConected()) conexao.fechaConexao();
        }
        
        
    }
   
    public void receberContas(String agencia){
        
         Conexao conexao = new Conexao(2525);
        try{
            
            conexao.conectaServidor();
            
            conexao.enviaString("listaContasPorAgencia");
            conexao.enviaString(agencia);
             
            String result = "";
            result = conexao.recebeString();
            
            conList = new DefaultListModel();
            conList.clear();
           
            if(result!=null){
                String[] quebra = result.split("&&");
               
                for(int i=0; i<quebra.length; i++){
                    conList.add(i, quebra[i]);
                }
                 
            }
            jListContas.setModel(conList);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro na busca da conta");
        }finally{
            if(conexao.isConected()) conexao.fechaConexao();
        }
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAgencias = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListContas = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DO BANCO");

        jLabel6.setText("AGENCIAS");

        jListAgencias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAgenciasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListAgencias);

        jButton4.setText("ADICIONAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("REMOVER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("CONTAS");

        jScrollPane2.setViewportView(jListContas);

        jButton6.setText("REMOVER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        jLabel3.setToolTipText("");

        textNome.setText("nomeBanco");

        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNome))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String numero = JOptionPane.showInputDialog("Digite o numero da agencia");
        
        if(numero.equals("")){
            JOptionPane.showMessageDialog(this,"Informe o numero da agencia");
        }else{
             Conexao conexao = new Conexao(2525);
            try{
            
                conexao.conectaServidor();

                conexao.enviaString("cadastroAgencia");
                conexao.enviaString(nomeBanco+"&&"+numero);

                String result = "";
                result = conexao.recebeString();

                if(result.equals("true")){
                    JOptionPane.showMessageDialog(this, "Cadastro realizado;");
                    receberAgencias();
                    
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Erro no cadastro da Agencia");
                }
            
            }catch(Exception e){
                 JOptionPane.showMessageDialog(this, "Erro no cadastro da Agencia\nerr:" + e);
            }finally{
                if(conexao.isConected()) conexao.fechaConexao();
            }
            
             
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
        if(jListAgencias.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(this, "Selecione uma agencia");
        }else{
            int dialogResult = JOptionPane.showConfirmDialog (null, "Você deseja remover a agencia " + jListAgencias.getSelectedValue() ,"ATENÇÃO",JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION){

                Conexao conexao = new Conexao(2525);
                try{
            
                    conexao.conectaServidor();

                    conexao.enviaString("removeAgencia");
                    conexao.enviaString(nomeBanco+"&&"+jListAgencias.getSelectedValue());

                    String result = "";
                    result = conexao.recebeString();

                    if(result.equals("true")){
                        JOptionPane.showMessageDialog(this, "Agencia removida;");
                        receberAgencias();


                    }else{
                        JOptionPane.showMessageDialog(this, "Erro ao remover Agencia");
                    }
            
                }catch(Exception e){
                     JOptionPane.showMessageDialog(this, "Erro ao remover Agencia \n err:" + e);
                }finally{
                    if(conexao.isConected()) conexao.fechaConexao();
                }
                
               

            }

        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        if(jListContas.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(this, "Selecione uma conta");
        }else{
            int dialogResult = JOptionPane.showConfirmDialog (null, "Você deseja remover a conta " + jListContas.getSelectedValue() ,"ATENÇÃO",JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION){

                Conexao conexao = new Conexao(2525);
                try{
            
                    conexao.conectaServidor();

                    conexao.enviaString("removeConta");
                    conexao.enviaString(jListContas.getSelectedValue());

                    String result = "";
                    result = conexao.recebeString();

                    if(result.equals("true")){
                        JOptionPane.showMessageDialog(this, "Conta removida;");
                        receberAgencias();


                    }else{
                        JOptionPane.showMessageDialog(this, "Erro ao remover Conta");
                    }
            
                }catch(Exception e){
                     JOptionPane.showMessageDialog(this, "Erro ao remover Conta \n err:" + e);
                }finally{
                    if(conexao.isConected()) conexao.fechaConexao();
                }
                
               

            }

        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jListAgenciasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAgenciasValueChanged
       
        receberContas(jListAgencias.getSelectedValue());
        
        
    }//GEN-LAST:event_jListAgenciasValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        LoginBanco log = new LoginBanco();
        log.setVisible(true);
        
        dispose();
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciaBanco gerencia = new GerenciaBanco(nomeBanco);
                gerencia.setVisible(true);
                
                while (gerencia.isActive()) {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(GerenciaBanco.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   gerencia.receberAgencias();
                    
                }
                
               
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListAgencias;
    private javax.swing.JList<String> jListContas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel textNome;
    // End of variables declaration//GEN-END:variables
}
